name: OV-PLC validate

on:
  pull_request:
  push:
    branches: [main]

jobs:
  validate:
    if: github.repository == 'NVIDIA-Omniverse/ovstream-internal'
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: NVIDIA-Omniverse/OV-PLC/.github/actions/ovplc-validate@main
